### ISSUE TITLE
docker not found

### ISSUE THREAD

**Issue by ReneHezser** [WAGO/azure-iot-edge#4]
With the newest version the container starts, but the docker-entrypoint.sh fails with "docker not found" in line 20.

    me@randomhost:~ $ sudo docker run --name azure-iot-edge-runtime -v /var/run/docker.sock:/var/run/docker.sock -v /config:/config wagoautomation/azure-iot-edge
    azure-iot-edge
    b5e5b8a864df
    /docker-entrypoint.sh: line 20: docker: command not found
    /docker-entrypoint.sh: line 21: docker: command not found
    Device "eth1" does not exist.
    ...

To have docker available from inside the container, add ```-v /usr/bin/docker:/usr/bin/docker``` to the mapped volumes.

**Comment by DirkMeihoefer** [comment]
README was updated.
